### ISSUE TITLE
Pressing tab crashes the game

### ISSUE THREAD

**Issue by Nixinova** [Beezig/Beezig#87]
**Describe the Bug**
Pressing tab crashes the game

**How to Reproduce**
- Log into a server
- Press tab
- Game crashes

**Expected Behavior**
The game to not crash

**Screenshots**
N/A

**System details**
 - OS: Windows 10 x64
 - Minecraft version: 1.8.9
 - 5zig version: 3.14.0
 - Beezig version: 7.0.0-Forge

**Additional context**
Crash log: [attached](https://github.com/Beezig/Beezig/files/6262242/log-.beezig-crash.txt)

```log
java.lang.NullPointerException: Unexpected error
	at eu.beezig.forge.api.BeezigAPI.getSetting(BeezigAPI.java:92)
	at eu.beezig.forge.badge.BadgeRenderer.shouldRenderTabBadge(BadgeRenderer.java:96)
	at net.minecraft.client.gui.GuiPlayerTabOverlay.func_175249_a(SourceFile:76)
```

**Comment by Nixinova** [comment]
Oh, should probably be transferred to https://github.com/Beezig/BeezigForge

**Comment by Nixinova** [comment]
Well, after seeing https://forum.hivemc.com/, it probably doesn't matter...
